apiVersion: apps/v1
kind: Deployment
metadata:
  name: version-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: version
      version: v2
  template:
    metadata:
      labels:
        app: version
        version: v2
    spec:
      containers:
        - name: spring-version
          image: spring-version:v2
          ports:
            - containerPort: 8080
