apiVersion: apps/v1
kind: Deployment
metadata:
  name: version-v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: version
      version: v1
  template:
    metadata:
      labels:
        app: version
        version: v1
    spec:
      containers:
        - name: spring-version
          image: spring-version:v1
          ports:
            - containerPort: 8080
